name: rust_core
description: Idiomatic Dart programming with predictable control flow, based off Rust's core library. 
  Includes types like Result, Option, Cells, and extensive methods/extensions.
version: 0.4.0
repository: https://github.com/mcmah309/rust_core

environment:
  sdk: ^3.3.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  #meta: ^1.11.0 # Comment out when pushing. Only used to help write "const" implementations internally

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
