name: rust_core
description: Implementation of Rust's core library in Dart. Types include Result, Option, Cells, Slices, Array, Iterators, and extensions. Facilitates functional programming and error handling.
version: 1.0.0
repository: https://github.com/mcmah309/rust_core

environment:
  sdk: ^3.3.0

# Add regular dependencies here.
dependencies:

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
