name: rust_core
description: Implementation of Rust's core library in a Dart friendly way. Usable by itself, but also a base for 
  libraries that want to build on Rust Semantics.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
  index_generator: ^3.4.1

index_generator:
  indexes:
    - path: lib
